Repository Valheim-Modding/Jotunn, pull requests merged in 2021-04, with the labels that each got.

#27 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#51 chore: Refactor most classes to adhere to naming conventions
  CONTRIBUTING.md
  JotunnBuildTask/AssemblyPublicizer.cs
  JotunnBuildTask/Program.cs
  JotunnDoc/Docs/InputDoc.cs
  JotunnDoc/JotunnDoc.cs
  JotunnDoc/Patches/ZRoutedRpcPatches.cs
  JotunnLib/Configs/LocalizationConfig.cs
  JotunnLib/Configs/SkillConfig.cs
  JotunnLib/ConsoleCommands/ClearCommand.cs
  JotunnLib/ConsoleCommands/HelpCommand.cs
  JotunnLib/Entities/ConsoleCommand.cs
  JotunnLib/Entities/Mock.cs
  JotunnLib/Events/PlayerPlacedPieceEventArgs.cs
  JotunnLib/Extensions/ItemExtensions.cs
  JotunnLib/Extensions/MockExtentions.cs
  JotunnLib/JotunnLib.csproj
  JotunnLib/Logger.cs
  JotunnLib/Main.cs
  JotunnLib/Manager.cs
  JotunnLib/Managers/CommandManager.cs
  JotunnLib/Managers/EventManager.cs
  JotunnLib/Managers/GUIManager.cs
  JotunnLib/Managers/InputManager.cs
  JotunnLib/Managers/ItemManager.cs
  JotunnLib/Managers/LocalizationManager.cs
  JotunnLib/Managers/MockManager.cs
  JotunnLib/Managers/PieceManager.cs
  JotunnLib/Managers/PrefabManager.cs
  JotunnLib/Managers/SaveManager.cs
  JotunnLib/Managers/SkillManager.cs
  JotunnLib/Managers/SynchronizationManager.cs
  JotunnLib/Managers/ZoneManager.cs
  JotunnLib/Patches/SkillsPatches.cs
  JotunnLib/Patches/ZNetPatches.cs
  JotunnLib/Patches/ZoneSystemPatches.cs
  JotunnLib/Utils/AssetUtils.cs
  JotunnLib/Utils/BepInExUtils.cs
  JotunnLib/Utils/BoneReorder.cs
  JotunnLib/Utils/ConfigurationManagerAttributes.cs
  JotunnLib/Utils/EventsHelper.cs
  JotunnLib/Utils/HashUtils.cs
  JotunnLib/Utils/ModCompatibility.cs
  JotunnLib/Utils/PatchInitAttribute.cs
  TestMod/TestMod.cs
Labels: code smell, refactor

#63 chore: Removed Load/Register conventions from managers, refactored methods to conform to naming conventions
  JotunnLib/Manager.cs
  JotunnLib/Managers/GUIManager.cs
  JotunnLib/Managers/InputManager.cs
  JotunnLib/Managers/LocalizationManager.cs
  JotunnLib/Managers/SkillManager.cs
  TestMod/TestMod.cs
Labels: refactor

#72 chore: Fixed naming inconsistencies with method names
  JotunnLib/Configs/SkillConfig.cs
  JotunnLib/JotunnLib.csproj
  JotunnLib/Logger.cs
  JotunnLib/Main.cs
  JotunnLib/Managers/CommandManager.cs
  JotunnLib/Managers/EventManager.cs
  JotunnLib/Managers/ItemManager.cs
  JotunnLib/Managers/PieceManager.cs
  JotunnLib/Managers/PrefabManager.cs
  JotunnLib/Managers/SaveManager.cs
  JotunnLib/Managers/SynchronizationManager.cs
  JotunnLib/Utils/ReflectionHelper.cs
  JotunnLib/Utils/ReflectionUtils.cs
  TestMod/TestMod.cs
Labels: refactor

#74 chore: Added naming fixes overlooked in last commit
  JotunnLib/Managers/LocalizationManager.cs
  JotunnLib/Managers/SkillManager.cs
Labels: refactor

#16 feat: Deserialization for skills and recipes
  JotunnLib/Configs/RecipeConfig.cs
  JotunnLib/Configs/SkillConfig.cs
  JotunnLib/Managers/ItemManager.cs
  JotunnLib/Managers/SkillManager.cs
  JotunnLib/Patches/ConsoleCommandsPatches.cs
  JotunnLib/Patches/SkillsPatches.cs
  JotunnLib/Utils/AssetUtils.cs
  TestMod/Assets/Translations/English/translations.json
  TestMod/Assets/recipes.json
  TestMod/Assets/skills.json
  TestMod/TestMod.cs
  TestMod/TestMod.csproj
Labels: enhancement

#109 Progress on KeyHints and Refactor of L10NManager
  JotunnLib/Configs/ButtonConfig.cs
  JotunnLib/Configs/KeyHintConfig.cs
  JotunnLib/Entities/CustomKeyHint.cs
  JotunnLib/Managers/GUIManager.cs
  JotunnLib/Managers/ItemManager.cs
  JotunnLib/Managers/LocalizationManager.cs
  TestMod/TestMod.cs
Labels: code smell

#114 chore: Updated release actions
  .github/workflows/docs.yaml
  .github/workflows/merge.yml
  .github/workflows/tag-release.yml
  JotunnLib/JotunnLib.csproj
Labels: devops

#115 docs: fixed SOME of the references in the docs
  JotunnLib/.gitignore
  JotunnLib/Configs/ItemConfig.cs
  JotunnLib/Configs/RecipeConfig.cs
  JotunnLib/Documentation/tutorials/commands/console-commands.md
  JotunnLib/Documentation/tutorials/data/assets.md
  JotunnLib/Documentation/tutorials/data/items.md
  JotunnLib/Documentation/tutorials/data/mocks.md
  JotunnLib/Documentation/tutorials/data/piece-categories.md
  JotunnLib/Documentation/tutorials/data/piece-tables.md
  JotunnLib/Documentation/tutorials/data/pieces.md
  JotunnLib/Documentation/tutorials/data/recipes.md
  JotunnLib/Documentation/tutorials/data/status-effects.md
  JotunnLib/Documentation/tutorials/data/toc.yml
  JotunnLib/Documentation/tutorials/inputs/overview.md
  JotunnLib/Documentation/tutorials/intro.md
  JotunnLib/Documentation/tutorials/toc.yml
  JotunnLib/Documentation/tutorials/utils/networkcompatibility.md
  JotunnLib/Documentation/tutorials/utils/overview.md
  JotunnLib/Documentation/tutorials/utils/toc.yml
Labels: documentation

#136 Update dev with changes from prod
  .github/workflows/docs.yaml
Labels: devops

#142 fix: skill IncreaseStep will now default to 1.0f
  JotunnLib/Configs/SkillConfig.cs
Labels: bug

#143 fix: closes #141
  JotunnLib/Managers/SkillManager.cs
  TestMod/TestMod.cs
Labels: bug

#145 Updated documentation for adding Skills and Recipes through JSON
  JotunnLib/Configs/RecipeConfig.cs
  JotunnLib/Configs/SkillConfig.cs
  JotunnLib/Documentation/tutorials/data/recipes.md
  JotunnLib/Documentation/tutorials/data/skills.md
Labels: documentation

#165 Started work on transition documentation
  JotunnLib/Documentation/index.md
  JotunnLib/Documentation/toc.yml
  JotunnLib/Documentation/transition/jotunnlib/assets.md
  JotunnLib/Documentation/transition/jotunnlib/overview.md
  JotunnLib/Documentation/transition/jotunnlib/prefabs.md
  JotunnLib/Documentation/transition/jotunnlib/register-events.md
  JotunnLib/Documentation/transition/jotunnlib/renaming.md
  JotunnLib/Documentation/transition/jotunnlib/toc.yml
  JotunnLib/Documentation/transition/jotunnlib/vs-project.md
  JotunnLib/Documentation/transition/overview.md
  JotunnLib/Documentation/transition/skillinjector/overview.md
  JotunnLib/Documentation/transition/toc.yml
  JotunnLib/Documentation/transition/valheimlib/overview.md
  JotunnLib/Documentation/transition/valheimlib/toc.yml
  JotunnLib/Documentation/transition/valheimlib/vs-project.md
Labels: documentation
